const {chromium}=require(process.env.VOCAB_PLAYWRIGHT_MODULE||'@playwright/test');
const assert=require('node:assert/strict');
const base=process.env.VOCAB_BASE_URL||'http://127.0.0.1:8765';
(async()=>{
 const browser=await chromium.launch();const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.clock.install();
 async function answer(){const c=await page.evaluate(()=>({mode:game.current.mode,truth:game.current.truth,index:game.current.choices.findIndex(c=>c.correct),answer:game.current.puzzle||answerVariants(game.current.word,game.current.target)[0],ids:game.current.pairs?.map(w=>w.id)}));
  if(c.mode==='choice')await page.locator(`[data-answer="${c.index}"]`).click();else if(c.mode==='truth')await page.locator(`[data-truth="${c.truth}"]`).click();else if(c.mode==='pairs'){for(const id of c.ids){await page.locator(`[data-pair="${id}"][data-lang="en"]`).click();await page.locator(`[data-pair="${id}"][data-lang="de"]`).click();}}else{await page.locator('#typed-answer').fill(c.answer);await page.locator('#answer-form').press('Enter');}}
 async function start(count=1,rounds=2,mode='choice'){await page.evaluate(({count,rounds,mode})=>{setup.count=count;setup.rounds=rounds;setup.mode=mode;setup.seconds=0;startGame()}, {count,rounds,mode});await page.locator('#begin-question').click();}
 async function recall(){await page.locator('#card-answer').fill(await page.evaluate(()=>{const c=cardSession.queue[0];return answerVariants(c.word,c.target)[0]}));await page.locator('#card-form').press('Enter');}
 for(const grade of [7,10,11]){
  await page.goto(`${base}/${grade}/`);
  for(const mode of ['choice','type','truth','scramble','pairs']){await start(1,2,mode);await answer();assert.equal(await page.evaluate(()=>game.turn),0);assert.equal(await page.evaluate(()=>game.phase),'feedback');await page.clock.runFor(1300);assert.equal(await page.evaluate(()=>game.turn),1);assert.equal(await page.evaluate(()=>game.phase),'question');assert.equal(await page.evaluate(()=>game.teams[0].score),100);}
  // Team hand-off does not start the next team's question timer.
  await start(2,1);await answer();await page.clock.runFor(1300);assert.equal(await page.evaluate(()=>game.turn),1);assert.equal(await page.evaluate(()=>game.phase),'ready');await page.locator('#begin-question').click();await answer();await page.clock.runFor(1300);assert.equal(await page.evaluate(()=>game.phase),'results');assert.deepEqual(await page.evaluate(()=>game.teams.map(t=>t.score)),[100,100]);
  // Incorrect answers and expired questions require deliberate continuation.
  await start();await page.evaluate(()=>submitAnswer(game.current.choices.findIndex(c=>!c.correct)));await page.clock.runFor(3000);assert.equal(await page.evaluate(()=>game.phase),'feedback');assert.equal(await page.evaluate(()=>game.turn),0);await page.locator('#next').click();await page.evaluate(()=>{setup.seconds=15;renderQuestion();game.current.deadline=performance.now()-1;tick()});await page.clock.runFor(3000);assert.equal(await page.evaluate(()=>game.turn),1);assert.match(await page.locator('.feedback h3').textContent(),/Time is up/);
  // A manual Next cannot also run the scheduled transition or skip a question.
  await start(1,3);await answer();await page.evaluate(()=>{const next=document.querySelector('#next');next.click();next.click()});await page.clock.runFor(2000);assert.equal(await page.evaluate(()=>game.turn),1);assert.equal(await page.evaluate(()=>game.phase),'question');
  // Pausing the game or hiding its tab keeps the feedback visible.
  await start();await answer();await page.locator('#quit').click();await page.clock.runFor(3000);assert.equal(await page.evaluate(()=>game.turn),0);await page.locator('#keep-playing').click();await page.clock.runFor(1300);assert.equal(await page.evaluate(()=>game.turn),1);
  await start();await answer();await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'))});await page.clock.runFor(3000);assert.equal(await page.evaluate(()=>game.turn),0);await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:false});document.dispatchEvent(new Event('visibilitychange'))});await page.clock.runFor(1300);assert.equal(await page.evaluate(()=>game.turn),1);
  await start();await answer();await page.locator('#quit').click();await page.locator('#confirm-quit').click();await page.clock.runFor(3000);assert.equal(await page.locator('#setup-form').count(),1);assert.equal(await page.evaluate(()=>game),null);
  // Cards auto-advance on correct recall; errors stay, and leaving cancels it.
  await page.evaluate(()=>{pendingMistakes.clear();setup.direction='mixed';startFlashcards(VOCAB.slice(0,2))});await recall();await page.clock.runFor(1300);assert.equal(await page.evaluate(()=>cardSession.completed),1);assert.equal(await page.evaluate(()=>cardSession.phase),'recall');await page.locator('#card-answer').fill('wrong answer');await page.locator('#card-form').press('Enter');await page.clock.runFor(3000);assert.equal(await page.evaluate(()=>cardSession.phase),'feedback');await page.locator('#next-card').click();await recall();await page.locator('#cards-exit').click();await page.clock.runFor(3000);assert.equal(await page.locator('#setup-form').count(),1);
  // The final game question opens mandatory review; final recall unlocks results.
  await start(1,2);await page.evaluate(()=>submitAnswer(game.current.choices.findIndex(c=>!c.correct)));await page.locator('#next').click();await answer();await page.clock.runFor(1300);assert.equal(await page.evaluate(()=>game.phase),'cards');await recall();await page.clock.runFor(1300);assert.equal(await page.locator('.ranking').count(),0);await recall();await page.clock.runFor(1300);assert.equal(await page.evaluate(()=>game.phase),'results');assert.equal(await page.evaluate(()=>game.teams[0].score),100);
 }
 assert.deepEqual(errors,[]);console.log('PASS: all grades and modes; correct-only progression, team hand-off, results, manual double-click protection, dialog/tab pause, leaving, cards and mandatory review.');await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
