const {chromium}=require(process.env.VOCAB_PLAYWRIGHT_MODULE||'@playwright/test');
const assert=require('node:assert/strict');
const base=process.env.VOCAB_BASE_URL||'http://127.0.0.1:8765';
(async()=>{
 const browser=await chromium.launch();const errors=[];
 for(const grade of [7,10,11]){
  const page=await browser.newPage({viewport:{width:375,height:950}});page.on('pageerror',e=>errors.push(e.message));await page.clock.install();
  await page.goto(`${base}/${grade}/?activity=learn`);await page.evaluate(()=>{localStorage.clear();loadLearning();loadMistakes();renderLearningSetup()});
  assert.equal(await page.locator('[name=learn-topic]:checked').count(),await page.locator('[name=learn-topic]').count());assert.equal(await page.locator('#learn-direction').inputValue(),'mixed');assert.equal(await page.locator('#seconds,#rounds,#team-count,#timer').count(),0);
  await page.evaluate(()=>{document.querySelectorAll('[name=learn-topic]').forEach(e=>e.checked=false)});await page.locator('#learn-begin').click();assert.match(await page.locator('#learning-error').textContent(),/Choose at least/);
  await page.locator('[name=learn-topic]').first().check();await page.locator('#learn-begin').click();assert.equal(await page.locator('.learn-word [lang=en]').count(),1);assert.equal(await page.locator('.learn-word [lang=de]').count(),1);assert.equal(await page.locator('#timer').count(),0);await page.locator('#learn-exit').click();
  await page.evaluate(()=>{setup.direction='mixed';startLearning(VOCAB.slice(0,2))});await page.locator('#learn-next').click();await page.locator('#learn-previous').click();assert.equal(await page.evaluate(()=>learningSession.index),0);await page.locator('#learn-next').click();await page.locator('#learn-next').click();
  const choose=async(correct)=>{const i=await page.evaluate(correct=>{const w=learningSession.block[learningSession.index],target=learningSession.index%2?'en':'de';const label=choiceLabel(w,target);return [...document.querySelectorAll('[data-learn-choice]')].findIndex(b=>(b.lastElementChild.textContent===label)===correct)},correct);assert(i>=0);await page.locator(`[data-learn-choice="${i}"]`).click();};
  await choose(false);await page.clock.runFor(1300);assert.equal(await page.evaluate(()=>learningSession.index),0);assert.equal(await page.evaluate(()=>pendingMistakes.size),1);await page.locator('#learn-continue').click();await choose(true);await page.clock.runFor(1300);assert.equal(await page.evaluate(()=>learningSession.index),1);await choose(true);await page.clock.runFor(1300);
  assert.equal(await page.evaluate(()=>cardSession.total),4);assert.deepEqual(await page.evaluate(()=>[...new Set(cardSession.queue.map(c=>c.target))].sort()),['de','en']);assert.equal(await page.evaluate(()=>learnedWords.size),0);
  await page.locator('#card-flip').click();assert.equal(await page.locator('#card-form button').isDisabled(),true);await page.locator('#card-flip').click();await page.locator('#card-answer').fill('incorrect recall');await page.locator('#card-form').press('Enter');await page.locator('#next-card').click();
  let n=0;while(await page.locator('#card-form').count()){assert(n++<12);const answer=await page.evaluate(()=>{const c=cardSession.queue[0];return answerVariants(c.word,c.target)[0]});await page.locator('#card-answer').fill(answer);await page.locator('#card-form').press('Enter');await page.clock.runFor(1300);}
  assert.equal(await page.evaluate(()=>learnedWords.size),2);assert.equal(await page.evaluate(()=>pendingMistakes.size),0);assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem(`vocab-learned-${GRADE}`)).length),2);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await page.screenshot({path:`/tmp/learning-complete-${grade}.png`,fullPage:true});await page.locator('#learn-block-next').click();assert.match(await page.locator('h1').textContent(),/Learning unit complete/);await page.locator('#learn-review').click();assert.equal(await page.evaluate(()=>learningSession.review),true);await page.locator('#learn-exit').click();await page.reload();assert.equal(await page.evaluate(()=>learnedWords.size),2);
  // Completed packs survive exit; new packs remain available. Six words produce a 5+1 split.
  await page.evaluate(()=>{learnedWords=new Set();startLearning(VOCAB.slice(0,6))});assert.equal(await page.evaluate(()=>learningSession.block.length),5);await page.evaluate(()=>completeLearningBlock());await page.locator('#learn-block-next').click();assert.equal(await page.evaluate(()=>learningSession.block.length),1);await page.locator('#learn-exit').click();assert.equal(await page.evaluate(()=>learnedWords.size),5);
  // Leaving recall cancels pending auto-progression and returns to the independent topics screen.
  await page.evaluate(()=>startLearning([VOCAB[5]]));await page.locator('#learn-next').click();await choose(true);await page.clock.runFor(1300);const answer=await page.evaluate(()=>{const c=cardSession.queue[0];return answerVariants(c.word,c.target)[0]});await page.locator('#card-answer').fill(answer);await page.locator('#card-form').press('Enter');await page.locator('#cards-exit').click();await page.clock.runFor(1300);assert.equal(await page.locator('#learning-form').count(),1);
  // Games do not require any learned vocabulary and retain all modes, directions and custom counts.
  await page.locator('#learning-back').click();await page.evaluate(()=>{learnedWords=new Set();renderSetup()});assert.equal(await page.locator('#mode').inputValue(),'mix');assert.equal(await page.locator('#rounds').inputValue(),'custom');await page.getByRole('button',{name:'Solo',exact:true}).click();await page.getByRole('button',{name:'Start match'}).click();assert.equal(await page.locator('#begin-question').count(),1);
  await page.goto(`${base}/${grade}/?activity=learn`);await page.setViewportSize({width:320,height:950});await page.addScriptTag({path:'/tmp/vocab-axe.min.js'});let axe=await page.evaluate(()=>axe.run(document,{runOnly:['wcag2a','wcag2aa','wcag21a','wcag21aa']}));assert.deepEqual(axe.violations.map(v=>v.id),[],`learning setup a11y grade ${grade}`);
  await page.evaluate(()=>{learnedWords=new Set();startLearning(VOCAB.slice(0,2))});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);axe=await page.evaluate(()=>axe.run(document,{runOnly:['wcag2a','wcag2aa','wcag21a','wcag21aa']}));assert.deepEqual(axe.violations.map(v=>v.id),[],`discovery a11y grade ${grade}`);await page.screenshot({path:`/tmp/learning-discover-${grade}.png`,fullPage:true});await page.close();
 }
 assert.deepEqual(errors,[]);await browser.close();console.log('PASS: independent learning and games in all grades; topic validation, bilingual discovery, recognition retries and auto-advance, two-direction recall and mistakes, checkpoint persistence, pack size, review, safe exit, mobile and accessibility.');
})().catch(e=>{console.error(e);process.exit(1)});
