/* Vocabulary transcribed from the two supplied pages. German meanings in
   the History words box are supplemented where the source has no translation. */
const GROUPS = {
  cultures: 'Across cultures', scotland: 'Scottish history',
  time: 'History · Time', relations: 'History · Relations',
  development: 'History · Development', systems: 'History · Systems', aggression: 'History · Aggression'
};
const RAW_VOCAB = {
  cultures: [
    ['rainbow','Regenbogen'],
    ['LGBTQIA+','Abkürzung für lesbisch, schwul, bisexuell, transgender, queer / questioning, intersexuell, asexuell / aromantisch und weitere Identitäten','', 'LGBTQIA+ refers to a range of sexual orientations and gender identities.'],
    ['similarity','Ähnlichkeit; Gemeinsamkeit'],
    ['pidgin','Pidgin; vereinfachte Kontaktsprache','Pidginsprache'],
    ['to simplify','vereinfachen'],
    ['pluralistic','pluralistisch; vielfältig'],
    ['mutual','gegenseitig','wechselseitig'],
    ['beneficial','nützlich','vorteilhaft; förderlich'],
    ['to proclaim','verkünden; erklären; ausrufen'],
    ['encounter','Begegnung; Zusammentreffen'],
    ['(song) lyrics','Liedtext','lyrics; song lyrics; Songtext']
  ],
  scotland: [
    ['to descend from','abstammen von; herstammen von'],
    ['relative','Verwandte / Verwandter','Verwandte; Verwandter; Verwandter/Verwandte'],
    ['to pledge allegiance','einen Treueschwur leisten','Treueschwur leisten; Treue schwören'],
    ['to pledge','geloben','versprechen'],
    ['exceptional','außergewöhnlich; Ausnahme-','aussergewöhnlich; besonders'],
    ['bravery','Tapferkeit; Mut'],
    ['loyalty','Treue; Loyalität'],
    ['surname','Nachname','Familienname'],
    ['Scot','Schotte / Schottin','Schotte; Schottin'],
    ['weaver','Weber / Weberin','Weber; Weberin'],
    ['to chop','hacken; klein schneiden','kleinschneiden; zerhacken'],
    ['heiress','Erbin'],
    ['alliance','Allianz; Bündnis'],
    ['rebel','Rebell / Rebellin; Aufständische / Aufständischer','Rebell; Rebellin; Aufständischer; Aufständische'],
    ['contribution','Beitrag; Beteiligung'],
    ['enlightenment','Aufklärung; Erleuchtung'],
    ['influential','einflussreich; maßgebend','massgebend; maßgeblich'],
    ['reason','Vernunft; Verstand']
  ],
  time: [
    ['age / era / period','Zeitalter; Ära; Epoche; Zeitraum','age; era; period'],
    ['the Age of Enlightenment','das Zeitalter der Aufklärung','Zeitalter der Aufklärung; age of enlightenment'],
    ['the Elizabethan Age','das elisabethanische Zeitalter','elisabethanisches Zeitalter; Elizabethan Age'],
    ['the Victorian Age','das viktorianische Zeitalter','viktorianisches Zeitalter; Victorian Age'],
    ['the Middle Ages','das Mittelalter','Mittelalter; Middle Ages'],
    ['prehistoric','prähistorisch; vorgeschichtlich'],
    ['ancient','antik; altertümlich','uralt'],
    ['medieval','mittelalterlich'],
    ['modern','modern; neuzeitlich'],
    ['contemporary','zeitgenössisch; gegenwärtig'],
    ['generation','Generation'],
    ['heyday','Höhepunkt; Blütezeit'],
    ['to date from','stammen aus','aus einer Zeit stammen; datieren aus'],
    ['to trace back to','zurückverfolgen bis; zurückführen auf','zurückgehen auf; zurückverfolgen auf']
  ],
  relations: [
    ['ancestor','Vorfahr / Vorfahrin','Vorfahr; Vorfahrin; Ahne'],
    ['ancestry','Abstammung; Herkunft'],
    ['heir','Erbe (Person)','Erbe; männlicher Erbe'],
    ['heritage','Kulturerbe; kulturelles Erbe','Erbe'],
    ['to inherit','erben'],
    ['inheritance','Erbschaft; geerbter Besitz','Erbe'],
    ['origin','Ursprung; Herkunft'],
    ['descent','Abstammung; Herkunft'],
    ['tradition','Tradition; Überlieferung'],
    ['to hand sth down','etwas weitergeben; etwas überliefern','weitergeben; überliefern; hand down; hand something down; to hand down; to hand something down']
  ],
  development: [
    ['to abolish','abschaffen'],
    ['to build','bauen; aufbauen'],
    ['to develop','entwickeln; sich entwickeln'],
    ['to emerge','auftauchen; entstehen'],
    ['to evolve','sich entwickeln','entwickeln; weiterentwickeln; sich weiterentwickeln'],
    ['to found / to establish','gründen; errichten','to found; found; to establish; establish'],
    ['to introduce','einführen']
  ],
  systems: [
    ['empire','Imperium; Reich; Weltreich'],
    ['kingdom','Königreich'],
    ['monarchy','Monarchie'],
    ['republic','Republik'],
    ['colony','Kolonie'],
    ['colonial','kolonial'],
    ['colonist','Kolonist / Kolonistin','Kolonist; Kolonistin'],
    ['to colonise','kolonisieren','colonize; to colonize'],
    ['colonisation','Kolonisierung; Kolonisation','colonization'],
    ['feudal system','Feudalsystem; Feudalwesen','feudal'],
    ['gentry','niederer Adel'],
    ['nobility','Adel'],
    ['knight','Ritter'],
    ['lord / lady','Lord / Lady; Adeliger / Adelige','lord; lady; Lord; Lady; Adeliger; Adelige; Adliger; Adlige'],
    ['peasant','Kleinbauer / Kleinbäuerin; Bauer / Bäuerin','Kleinbauer; Kleinbäuerin; Bauer; Bäuerin'],
    ['serf','Leibeigener / Leibeigene','Leibeigener; Leibeigene']
  ],
  aggression: [
    ['to assassinate','ermorden'],
    ['assassination','Attentat; Ermordung'],
    ['to attack','angreifen; attackieren'],
    ['to conquer','erobern'],
    ['conqueror','Eroberer / Eroberin','Eroberer; Eroberin'],
    ['to defeat','besiegen; schlagen'],
    ['armed','bewaffnet'],
    ['to destroy','zerstören'],
    ['destruction','Zerstörung'],
    ['to execute','hinrichten'],
    ['execution','Hinrichtung'],
    ['to imprison','inhaftieren; einsperren','verhaften'],
    ['imprisonment','Inhaftierung; Gefangenschaft','Haft; Freiheitsentzug'],
    ['to invade','einmarschieren; eindringen','einfallen in; einmarschieren in'],
    ['invasion','Invasion; Einmarsch'],
    ['to rebel','rebellieren; sich auflehnen','aufbegehren'],
    ['rebellion','Rebellion; Aufstand'],
    ['to revolt','revoltieren; sich auflehnen','aufbegehren'],
    ['to revolutionise','revolutionieren','revolutionize; to revolutionize'],
    ['revolution','Revolution'],
    ['revolutionary','revolutionär'],
    ['to riot','randalieren'],
    ['riot','Aufruhr; Ausschreitung','Krawall; Randale'],
    ['rioter','Randalierer / Randaliererin','Randalierer; Randaliererin']
  ]
};
const VOCAB = Object.entries(RAW_VOCAB).flatMap(([group, rows]) => rows.map((r, index) => ({id:`${group}-${index}`, group, en:r[0], de:r[1], aliases:(r[2]||'').split(';').map(s=>s.trim()).filter(Boolean), note:r[3]||''})));
